name: 'buildkit-action'
description: 'Build and push a container image using buildkit'
author: 'Jacky Nguyen'
inputs:
  buildkitImage:
    required: false
    description: 'Docker image reference for buildkit'
    default: 'shopstic/buildkit:0.8.2'
  context:
    required: true
    description: 'Absolute path to build context'
  image:
    required: true
    description: 'Image name to build and push'
  tag:
    required: true
    description: 'Image tag to build and push'
  additionalTags:
    required: false
    description: 'Additional image tags to push (comma separated)'
  cacheTag:
    required: false
    description: 'Cache tag to export and import'
    default: '__buildkit_cache__'
  skipIfExists:
    required: false
    description: 'Whether to skip building the image if it already exists in the registry'
    default: 'false'
outputs:
  image:
    description: 'Image name that has been built and pushed'
  tag:
    description: 'Image tag that has been built and pushed'
runs:
  using: 'node12'
  main: 'dist/index.js'
