name: 'buildkit-action'
description: 'Build and push a container image using buildkit'
author: 'Jacky Nguyen'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
